const A = (()=>{
  const C = window.ACADEMY_CATALOG;
  const PATHS = C.paths;
  const pathMap = Object.fromEntries(PATHS.map(p=>[p.id,p]));
  const featureMap = Object.fromEntries(C.features.map(f=>[f.id,f]));
  const KEY='v_academy_v31_state';
  const defaultState={profile:{name:'',email:'',role:'Business Development Manager',permission:'Learner'},view:'dashboard',activePath:'foundations',activeLesson:'start_day',activeFeature:'feature_gmail',completed:{},confidence:{},pins:[],journey:[],adminUnlocked:false};
  let s = load();
  function load(){try{return {...defaultState,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch(e){return {...defaultState}}}
  function save(){localStorage.setItem(KEY,JSON.stringify(s));}
  function esc(x){return String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
  function enc(x){return encodeURIComponent(x)} function dec(x){return decodeURIComponent(x)}
  function allKeys(){return PATHS.flatMap(p=>Object.keys(p.lessons).map(id=>p.id+'__'+id));}
  function pctPath(pathId){const p=pathMap[pathId];const ids=Object.keys(p.lessons).map(id=>pathId+'__'+id);return ids.length?Math.round(ids.filter(k=>s.completed[k]).length/ids.length*100):0}
  function totalProgress(){const ids=allKeys();return ids.length?Math.round(ids.filter(k=>s.completed[k]).length/ids.length*100):0}
  function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.style.display='block';clearTimeout(t._tm);t._tm=setTimeout(()=>t.style.display='none',1800)}
  function log(event,data={}){if(!s.profile.email)return;const profile={email:s.profile.email,name:s.profile.name,role:s.profile.role,currentCourse:s.activePath,overallProgress:totalProgress()};AcademySync.post({profile,event,data});}
  function journey(type,name,course){s.journey.unshift({ts:new Date().toLocaleString('en-AU'),type,name,course:course||''});s.journey=s.journey.slice(0,100);save();}
  function modal(title,msg,icon='🎉'){document.getElementById('modal').className='modal';document.getElementById('modal').innerHTML=`<div class="modalCard"><div class="icon">${icon}</div><h2>${title}</h2><p>${msg}</p><button class="btn gold" onclick="A.closeModal()">Continue</button></div>`}
  function closeModal(){document.getElementById('modal').className='modal hidden'}
  function copy(txt){navigator.clipboard.writeText(txt);toast('Copied')}
  function render(){const catalog=['dashboard','learningPaths','features','toolbox','progress','settings','admin','featureDetail'].includes(s.view);document.getElementById('app').className='app '+(catalog?'catalogOnly':'');document.getElementById('app').innerHTML=left()+middle()+main();bind();}
  function left(){const adminVisible=(s.profile.permission==='Administrator'||s.profile.permission==='Trainer'||s.adminUnlocked);return `<aside class="left"><div class="brand"><img src="assets/vanilla-logo.png"><div><h1>${esc(ACADEMY_CONFIG.academyName)}</h1><p>${esc(ACADEMY_CONFIG.subtitle)}</p></div></div><div class="profile"><strong>${esc(s.profile.name||'Set up profile')}</strong><span class="small">${esc(s.profile.role||'Required before syncing')}</span><div class="progressbar"><div class="progressfill" style="width:${totalProgress()}%"></div></div><span class="small">Overall progress ${totalProgress()}%</span></div><button class="navBtn ${s.view==='dashboard'?'active':''}" data-view="dashboard">🏠 Dashboard</button><button class="navBtn ${s.view==='learningPaths'||s.view==='course'?'active':''}" data-view="learningPaths">🎓 Learning Paths</button><button class="navBtn ${s.view==='features'||s.view==='featureDetail'?'active':''}" data-view="features">✨ AI Features</button><button class="navBtn ${s.view==='toolbox'?'active':''}" data-view="toolbox">🧰 Toolbox</button><button class="navBtn ${s.view==='progress'?'active':''}" data-view="progress">📈 Progress</button><button class="navBtn ${s.view==='settings'?'active':''}" data-view="settings">⚙ Settings</button>${adminVisible?`<button class="navBtn ${s.view==='admin'?'active':''}" data-view="admin">🔐 Administration</button>`:''}<div class="pinList"><strong>📌 Pinned tools</strong><div id="pinList">${s.pins.map((p,i)=>`<div class="pin" draggable="true" data-pin-index="${i}"><span>${esc(p)}</span><button data-unpin="${esc(p)}">×</button></div>`).join('')||'<p class="small">No pinned tools yet.</p>'}</div></div><p class="small">Version ${esc(ACADEMY_CONFIG.version)}</p></aside>`}
  function middle(){if(s.view!=='course')return '<aside class="middle blank"></aside>';const p=pathMap[s.activePath];return `<aside class="middle" id="courseMenu"><div class="courseTitle">${p.icon} ${esc(p.title)}</div><div class="progressbar"><div class="progressfill" style="width:${pctPath(p.id)}%"></div></div><p class="small">${pctPath(p.id)}% complete</p>${p.modules.map(m=>`<div class="moduleHead">${esc(m.heading)}</div>${m.lessons.map(id=>{const l=p.lessons[id];const done=s.completed[p.id+'__'+id];return `<button class="lessonBtn ${id===s.activeLesson?'active':''} ${done?'done':''}" data-lesson="${id}"><span class="dot">${done?'✓':'○'}</span><span>${l.icon||'•'} ${esc(l.title)}<br><span class="small">${esc(l.time)}</span></span></button>`}).join('')}`).join('')}</aside>`}
  function main(){return `<main class="main">${({dashboard,learningPaths,course:lesson,features,featureDetail,toolbox,progress,settings,admin}[s.view]||dashboard)()}</main>`}
  function dashboard(){const n=nextLesson(), p=pathMap[n.path], l=p.lessons[n.lesson];return `<section class="panel hero"><div class="eyebrow">Dashboard</div><h2>Welcome back, ${esc(s.profile.name||'there')}</h2><p>Recommended next step based on your progress.</p><div class="pathCard"><div><h4>${p.icon} ${esc(p.title)}</h4><p><b>Next workflow:</b> ${esc(l.title)}</p><p>${esc(l.why)}</p><span class="pill">${esc(l.time)}</span></div><button class="btn gold" data-open-path="${p.id}" data-open-lesson="${l.id}">${s.completed[p.id+'__'+l.id]?'Review':'Start / Continue'}</button></div></section><section class="panel"><h3>Pinned tools</h3>${s.pins.length?`<div class="grid">${s.pins.map(p=>`<div class="card"><h4>📌 ${esc(p)}</h4><button class="btn secondary" data-tool="${esc(p)}">Open</button></div>`).join('')}</div>`:'<p>No pinned tools yet. Pin useful workflows from lessons, AI Features or Toolbox.</p>'}</section><section class="panel"><h3>What changed in V3.1</h3><div class="list"><div class="tick">Canvas removed.</div><div class="tick">AI Foundations is now workflow-first: Start Your Day, Communicate, Documents, Answers, Vanilla Knowledge and Work Smarter.</div><div class="tick">AI Features still exist, but they support workflows instead of becoming the whole curriculum.</div><div class="tick">Calendar and Gmail include practical prompt packs.</div></div></section>`}
  function nextLesson(){for(const p of PATHS){for(const id of Object.keys(p.lessons)){if(!s.completed[p.id+'__'+id])return {path:p.id,lesson:id}}}return {path:'foundations',lesson:Object.keys(pathMap.foundations.lessons)[0]}}
  function learningPaths(){const group = g => PATHS.filter(p=>p.category===g).map(p=>`<div class="pathCard"><div><h4>${p.icon} ${esc(p.title)}</h4><p>${esc(p.description)}</p><span class="pill">${pctPath(p.id)}% complete</span><span class="pill">${esc((p.recommendedFor||[]).join(', '))}</span></div><button class="btn gold" data-open-path="${p.id}">${pctPath(p.id)===100?'Review':'Open'}</button></div>`).join('');return `<section class="panel hero"><div class="eyebrow">Learning Paths</div><h2>Choose the work you want to learn</h2><p>Learning Paths are structured training. AI Features explain individual tools. Toolbox gives reusable workflows.</p></section><section class="panel"><h3>Core Learning</h3>${group('Core Learning')}</section><section class="panel"><h3>Role Learning</h3>${group('Role Learning')}</section>`}
  function lesson(){const p=pathMap[s.activePath], l=p.lessons[s.activeLesson], key=p.id+'__'+l.id;return `<div class="breadcrumb"><button class="btn secondary" data-view="learningPaths">Learning Paths</button> › ${esc(p.title)} › ${esc(l.title)}</div><section class="panel hero"><div class="eyebrow">${esc(p.title)}</div><h2>${l.icon||''} ${esc(l.title)}</h2><div class="tools"><span class="pill">Suggested time: ${esc(l.time)}</span>${(l.tools||[]).map(t=>`<span class="toolChip">${esc(t)}</span>`).join('')}<button class="btn secondary" data-pin-tool="${esc(l.title)}">📌 Pin Workflow</button></div></section>${lessonBody(l)}<section class="panel"><h3>Complete this workflow</h3><p class="small">This is your own progress record, not a test. Complete it only after genuinely trying the practical mission or walking through it with a realistic example.</p><div class="confidence"><button class="btn secondary" data-confidence="Confident">😊 Confident</button><button class="btn secondary" data-confidence="Getting there">🙂 Getting there</button><button class="btn secondary" data-confidence="Need practice">😐 Need practice</button></div><div class="completeRow"><span class="status ${s.completed[key]?'done':''}">${s.completed[key]?'Complete':'Not complete yet'}</span><button class="btn ${s.completed[key]?'secondary':'green'}" data-complete="${key}">${s.completed[key]?'Mark incomplete':'Complete mission'}</button></div></section>`}
  function lessonBody(l){return `<section class="panel"><h3>Why this matters</h3><p>${esc(l.why)}</p><div class="grid2"><div class="card"><h4>Use this when</h4><ul>${(l.when||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div><div class="card"><h4>Be careful when</h4><ul>${(l.avoid||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div></div></section><section class="panel"><h3>Prompt pack</h3>${(l.prompts||[]).map(p=>promptCard(p.title,p.text)).join('')}</section><section class="panel"><h3>Mission</h3><div class="callout"><b>Do this with a real or realistic work example</b><ol>${(l.mission||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ol></div></section>`}
  function promptCard(title,text){return `<div class="promptCard"><div class="promptHead"><span>${esc(title)}</span><button class="btn secondary" data-copy="${enc(text)}">Copy</button></div><div class="promptBody"><div class="prompt">${esc(text)}</div></div></div>`}
  function features(){return `<section class="panel hero"><div class="eyebrow">AI Features</div><h2>Know the tools, then use them in workflows</h2><p>These pages explain what each feature does, where it actually helps Vanilla staff, when not to use it, and prompt examples.</p></section><section class="panel"><div class="grid">${C.features.map(f=>`<div class="card"><h4>${f.icon} ${esc(f.title)}</h4><p>${esc(f.summary)}</p><button class="btn secondary" data-feature="${f.id}">Open</button></div>`).join('')}</div></section>`}
  function featureDetail(){const f=featureMap[s.activeFeature]||C.features[0];return `<div class="breadcrumb"><button class="btn secondary" data-view="features">AI Features</button> › ${esc(f.title)}</div><section class="panel hero"><div class="eyebrow">AI Feature</div><h2>${f.icon} ${esc(f.title)}</h2><p>${esc(f.summary)}</p><button class="btn secondary" data-pin-tool="${esc(f.title)}">📌 Pin feature</button></section><section class="panel"><h3>Why it matters</h3><p>${esc(f.why)}</p><div class="grid2"><div class="card"><h4>Good uses</h4><ul>${(f.use||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div><div class="card"><h4>Avoid / watch out</h4><ul>${(f.avoid||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div></div></section><section class="panel"><h3>Prompt examples</h3>${(f.prompts||[]).map(p=>promptCard(p.title,p.text)).join('')}</section>`}
  function toolbox(){return `<section class="panel hero"><div class="eyebrow">Toolbox</div><h2>Reusable Vanilla workflows</h2><p>Pin the workflows you actually use. There is no hard limit, but if you pin everything it becomes noise.</p></section><section class="panel"><div class="grid">${C.tools.map(t=>`<div class="card"><h4>🧰 ${esc(t.title)}</h4><p>${esc(t.description)}</p><button class="btn secondary" data-copy="${enc(t.prompt)}">Copy Workflow</button> <button class="btn secondary" data-pin-tool="${esc(t.title)}">📌 Pin</button></div>`).join('')}</div></section>`}
  function progress(){return `<section class="panel hero"><div class="eyebrow">Progress</div><h2>My progress</h2><p>Your local view of learning history. Google Sheet stores meaningful events when syncing is enabled.</p></section><section class="panel"><h3>Learning path progress</h3>${PATHS.map(p=>`<div class="tick"><b>${p.icon} ${esc(p.title)}</b><div class="progressbar"><div class="progressfill" style="width:${pctPath(p.id)}%"></div></div>${pctPath(p.id)}%</div>`).join('')}</section><section class="panel"><h3>Journey log</h3>${s.journey.map(j=>`<div class="tick"><b>${esc(j.ts)}</b> — ${esc(j.type)}: ${esc(j.name)} ${j.course?`(${esc(j.course)})`:''}</div>`).join('')||'<p>No activity yet.</p>'}</section><section class="panel"><h3>Confidence</h3>${Object.entries(s.confidence).map(([k,v])=>`<div class="tick">${esc(k)}: <b>${esc(v)}</b></div>`).join('')||'<p>No confidence entries yet.</p>'}</section>`}
  function settings(){const eligible=s.profile.permission==='Administrator'||s.profile.permission==='Trainer';return `<section class="panel hero"><div class="eyebrow">Settings</div><h2>Profile & access</h2></section><section class="panel"><div class="formGrid"><div><label>Name</label><input id="name" value="${esc(s.profile.name)}"></div><div><label>Email</label><input id="email" value="${esc(s.profile.email)}"></div><div><label>Learning role</label><select id="role">${['Business Development Manager','Property Manager','Assistant Property Manager','Administration','Operations','Management','AI Specialist'].map(r=>`<option ${s.profile.role===r?'selected':''}>${r}</option>`).join('')}</select></div><div><label>Current access</label><input value="${esc(s.profile.permission||'Learner')}" disabled></div></div><div class="tools"><button class="btn gold" id="saveProfile">Save profile</button><button class="btn secondary" id="exportData">Export backup</button><button class="btn secondary" id="importData">Import backup</button><button class="btn red" id="resetLocal">Reset local progress</button></div></section>${eligible?`<section class="panel"><h3>Administrator access</h3><p>Only trainer/administrator emails can unlock this. PIN is checked by Apps Script.</p><input id="adminPin" placeholder="Administrator PIN"><div class="tools"><button class="btn secondary" id="unlockAdmin">Unlock administration</button><button class="btn secondary" id="removeAdmin">Remove local admin access</button></div></section>`:`<section class="panel"><h3>Administrator access</h3><p>This email is currently a Learner. If you should have admin access, add your email to the Permissions tab and save profile again.</p></section>`}`}
  function admin(){if(!(s.profile.permission==='Administrator'||s.profile.permission==='Trainer'||s.adminUnlocked))return `<section class="panel"><h2>Administration unavailable</h2><p>This account does not have administrator permission.</p></section>`;return `<section class="panel hero"><div class="eyebrow">Administration</div><h2>Team dashboard & maintenance</h2><p>Use controlled actions instead of editing random rows in Google Sheets.</p></section><section class="panel"><h3>Admin tools</h3><div class="tools"><button class="btn secondary" data-admin-action="purge_lesson_opened">Purge noisy lesson_opened events</button><button class="btn secondary" data-admin-action="rebuild_summary">Rebuild summaries</button><button class="btn secondary" data-admin-action="remove_duplicates">Remove duplicates</button></div></section>`}
  function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{s.view=b.dataset.view;save();render();scrollTop()});document.querySelectorAll('[data-open-path]').forEach(b=>b.onclick=()=>{const p=pathMap[b.dataset.openPath];s.activePath=p.id;s.activeLesson=b.dataset.openLesson||firstIncomplete(p);s.view='course';save();render();scrollTop()});document.querySelectorAll('[data-lesson]').forEach(b=>b.onclick=()=>{const menu=document.getElementById('courseMenu'),y=menu?menu.scrollTop:0;s.activeLesson=b.dataset.lesson;save();render();const m=document.getElementById('courseMenu');if(m)m.scrollTop=y;scrollTop()});document.querySelectorAll('[data-feature]').forEach(b=>b.onclick=()=>{s.activeFeature=b.dataset.feature;s.view='featureDetail';save();render();scrollTop()});document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>copy(dec(b.dataset.copy)));document.querySelectorAll('[data-pin-tool]').forEach(b=>b.onclick=()=>pin(b.dataset.pinTool));document.querySelectorAll('[data-unpin]').forEach(b=>b.onclick=()=>unpin(b.dataset.unpin));document.querySelectorAll('[data-complete]').forEach(b=>b.onclick=()=>toggleComplete(b.dataset.complete));document.querySelectorAll('[data-confidence]').forEach(b=>b.onclick=()=>setConfidence(b.dataset.confidence));document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>{s.view='toolbox';save();render();toast('Open from Toolbox')});const sp=document.getElementById('saveProfile');if(sp)sp.onclick=saveProfile;const ex=document.getElementById('exportData');if(ex)ex.onclick=exportData;const im=document.getElementById('importData');if(im)im.onclick=importData;const rs=document.getElementById('resetLocal');if(rs)rs.onclick=resetLocal;const ua=document.getElementById('unlockAdmin');if(ua)ua.onclick=unlockAdmin;const ra=document.getElementById('removeAdmin');if(ra)ra.onclick=()=>{s.adminUnlocked=false;save();render();toast('Admin access removed')};document.querySelectorAll('[data-admin-action]').forEach(b=>b.onclick=()=>adminAction(b.dataset.adminAction));bindDragPins();}
  function firstIncomplete(p){for(const id of Object.keys(p.lessons)){if(!s.completed[p.id+'__'+id])return id}return Object.keys(p.lessons)[0]}
  function toggleComplete(key){const [pathId,lessonId]=key.split('__');const p=pathMap[pathId], l=p.lessons[lessonId];if(s.completed[key]){delete s.completed[key];journey('Uncompleted',l.title,p.title);log({type:'mission_uncompleted',course:p.title,lessonId:lessonId,name:'Uncompleted '+l.title});toast('Marked incomplete')}else{s.completed[key]=new Date().toISOString();journey('Completed',l.title,p.title);log({type:'mission_completed',course:p.title,lessonId:lessonId,name:'Completed '+l.title});modal(l.title+' complete',l.congrats,'✅');if(pctPath(pathId)===100){journey('Completed path',p.title,p.title);log({type:'path_completed',course:p.title,itemId:pathId+'_certificate',itemName:p.certificate,certificateId:pathId+'_certificate',certificateName:p.certificate,name:p.title+' completed'});setTimeout(()=>modal(p.title+' completed',`Excellent work. You completed ${p.title}. Your progress and certificate event have been recorded.`, '🏆'),700)}}save();render();}
  function setConfidence(val){const p=pathMap[s.activePath],l=p.lessons[s.activeLesson];s.confidence[p.title+' / '+l.title]=val;journey('Confidence',val,p.title+' / '+l.title);log({type:'confidence_selected',course:p.title,lessonId:l.id,name:'Confidence: '+val},{confidence:val});save();toast('Confidence saved')}
  function pin(tool){if(!s.pins.includes(tool))s.pins.push(tool);journey('Pinned',tool);log({type:'tool_pinned',course:'Toolbox',itemName:tool,name:'Pinned '+tool});save();render();toast('Pinned')}
  function unpin(tool){s.pins=s.pins.filter(p=>p!==tool);journey('Unpinned',tool);log({type:'tool_unpinned',course:'Toolbox',itemName:tool,name:'Unpinned '+tool});save();render()}
  function bindDragPins(){const list=document.getElementById('pinList');if(!list)return;let drag=null;list.querySelectorAll('.pin').forEach(el=>{el.ondragstart=()=>{drag=el;el.classList.add('dragging')};el.ondragend=()=>{el.classList.remove('dragging');s.pins=[...list.querySelectorAll('.pin')].map(e=>e.querySelector('span').textContent);save()};el.ondragover=e=>{e.preventDefault();if(drag&&drag!==el){const r=el.getBoundingClientRect();(e.clientY>r.top+r.height/2)?el.after(drag):el.before(drag)}}})}
  function saveProfile(){s.profile.name=document.getElementById('name').value.trim();s.profile.email=document.getElementById('email').value.trim().toLowerCase();s.profile.role=document.getElementById('role').value;save();log({type:'profile_saved',course:'Profile',name:'Profile saved'});AcademySync.jsonp('permission',{email:s.profile.email}).then(r=>{if(r&&r.permission){s.profile.permission=r.permission;save();render();toast('Profile saved: '+r.permission)}else{render();toast('Profile saved')}})}
  function unlockAdmin(){const pin=document.getElementById('adminPin').value.trim();AcademySync.jsonp('checkAdmin',{email:s.profile.email,pin}).then(r=>{if(r&&r.ok){s.adminUnlocked=true;s.profile.permission=r.permission||s.profile.permission;save();render();toast('Administration unlocked')}else toast((r&&r.error)||'Access denied')})}
  function adminAction(action){const pin=prompt('Administrator PIN');if(!pin)return;AcademySync.jsonp('adminAction',{email:s.profile.email,pin,adminAction:action}).then(r=>toast(r&&r.ok?'Admin action completed':'Admin action failed'))}
  function exportData(){const blob=new Blob([JSON.stringify(s,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='v-academy-backup.json';a.click();log({type:'backup_exported',course:'Settings',name:'Backup exported'})}
  function importData(){const i=document.createElement('input');i.type='file';i.accept='application/json';i.onchange=()=>{const f=i.files[0];const r=new FileReader();r.onload=()=>{try{s={...defaultState,...JSON.parse(r.result)};save();render();toast('Backup imported');log({type:'backup_imported',course:'Settings',name:'Backup imported'})}catch(e){toast('Invalid backup')}};r.readAsText(f)};i.click()}
  function resetLocal(){if(confirm('Reset local progress on this browser? Google Sheet history is not deleted.')){s={...defaultState,profile:s.profile};save();render();toast('Local progress reset');log({type:'reset_progress',course:'Settings',name:'Local reset'})}}
  function scrollTop(){setTimeout(()=>{const m=document.querySelector('.main');if(m)m.scrollTo({top:0,behavior:'smooth'});window.scrollTo({top:0,behavior:'smooth'})},0)}
  return {render,closeModal};
})();
document.addEventListener('DOMContentLoaded',()=>A.render());
